name: Automated API tests using Postman CLI simpleBookAPI

on: push

env: 
  BASED_URI: 'https://simple-books-api.glitch.me'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - name: Install Newman
        run: |
          npm install -g newman
      - name: Install Newman reporter
        run: |
          npm install -g newman-reporter-html
      - name: Run API tests
        run: |
          newman run "https://winter-star-126497.postman.co/workspace/CI~e58e311d-c3f1-4844-b084-317c929fbf3d/collection/19276184-120be920-70dc-40f0-8bf1-9c660ac7e49a" --reporters cli,html --reporter-html-export "report.html"
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.html